### ISSUE TITLE
Can't get it to work at all

### ISSUE THREAD

**Issue by elutz** [miyako/4d-class-marked#1]
I want to test the class to understand the principle behind it. But I have some difficulties to get class to deliver the right results, or a result at all.
It takes some time and the delivered result of `$marked.generate` is not defined. The web area never seems to be called, the event `"On End URL Loading"` never happened.
What am I doing wrong?
This is on Windows with 4D 20R4.

**Comment by miyako** [comment]
there is an unnecessary `.folder("Contents")` in

https://github.com/miyako/4d-class-marked/blob/1a40c7ac58f7dd6cbd48fff2d8198d0a9eea2c36/marked/Project/Sources/Classes/_Marked.4dm#L12
